//constant variables for switch statement for actions

export const CONST = {
  CREATE_FEED: 'CREATE_FEED',
  LOAD_FEED_SUCCESS: 'LOAD_FEED_SUCCESS',
  LOAD_FEEDLINK_SUCCESS: 'LOAD_FEEDLINK_SUCCESS',
  SAVE_FEEDLINK_SUCCESS: 'SAVE_FEEDLINK_SUCCESS',
  BEGIN_AJAX_CALL: 'BEGIN_AJAX_CALL',
  AJAX_CALL_ERROR: 'AJAX_CALL_ERROR',
  LOAD_RSSFEED_SUCCESS: 'LOAD_RSSFEED_SUCCESS',
  DECODE_UNICODE: 'DECODE_UNICODE'
};
